name: smartroom
description: "A Flutter project for room environment monitoring and control."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # MQTT client for MQTT communication
  mqtt_client: any
  provider: ^6.0.0
  http: ^0.13.3
  fl_chart: ^0.63.0
  intl: ^0.17.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true

  # Add assets configuration for image files
  assets:
    - assets/images/logo.png
